const bookMockDataA = [
  {
    "Book Id": 35656180,
    Title:
      "The 57 Bus: A True Story of Two Teenagers and the Crime That Changed Their Lives",
    Author: "Dashka Slater",
    "Author l-f": "Slater, Dashka",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 4,
    "Average Rating": 4.2,
    Publisher: "Farrar, Straus and Giroux (BYR)",
    Binding: "Kindle Edition",
    "Number of Pages": 308,
    "Year Published": 2017,
    "Original Publication Year": 2017,
    "Date Read": "2020/12/30",
    "Date Added": "2020/12/28",
    Bookshelves: "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 1,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
  {
    "Book Id": 52425299,
    Title: "Shakespeare for Squirrels: A Novel",
    Author: "Christopher Moore",
    "Author l-f": "Moore, Christopher",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 4,
    "Average Rating": 3.9,
    Publisher: "William Morrow",
    Binding: "Kindle Edition",
    "Number of Pages": 288,
    "Year Published": 2020,
    "Original Publication Year": 2020,
    "Date Read": "",
    "Date Added": "2020/02/18",
    Bookshelves: "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 1,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
];

const bookMockDataB = [
  {
    "Book Id": 35656180,
    Title:
      "The 57 Bus: A True Story of Two Teenagers and the Crime That Changed Their Lives",
    Author: "Dashka Slater",
    "Author l-f": "Slater, Dashka",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 4,
    "Average Rating": 4.2,
    Publisher: "Farrar, Straus and Giroux (BYR)",
    Binding: "Kindle Edition",
    "Number of Pages": 308,
    "Year Published": 2017,
    "Original Publication Year": 2017,
    "Date Read": "2020/12/30",
    "Date Added": "2020/12/28",
    Bookshelves: "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 1,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
  {
    "Book Id": 52425299,
    Title: "Shakespeare for Squirrels: A Novel",
    Author: "Christopher Moore",
    "Author l-f": "Moore, Christopher",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 4,
    "Average Rating": 3.9,
    Publisher: "William Morrow",
    Binding: "Kindle Edition",
    "Number of Pages": 288,
    "Year Published": 2020,
    "Original Publication Year": 2020,
    "Date Read": "",
    "Date Added": "2020/02/18",
    Bookshelves: "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 1,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
  {
    "Book Id": 18208416,
    Title: "The Serpent of Venice",
    Author: "Christopher Moore",
    "Author l-f": "Moore, Christopher",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 3,
    "Average Rating": 3.88,
    Publisher: "William Morrow & Company",
    Binding: "Kindle Edition",
    "Number of Pages": 336,
    "Year Published": 2014,
    "Original Publication Year": 2014,
    "Date Read": "2020/12/22",
    "Date Added": "2020/12/11",
    Bookshelves: "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 1,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
  {
    "Book Id": 54447930,
    Title: "Ready Player Two (Ready Player One, #2)",
    Author: "Ernest Cline",
    "Author l-f": "Cline, Ernest",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 0,
    "Average Rating": 3.54,
    Publisher: "Ballantine Books",
    Binding: "Kindle Edition",
    "Number of Pages": 384,
    "Year Published": 2020,
    "Original Publication Year": 2020,
    "Date Read": "",
    "Date Added": "",
    Bookshelves: "to-read",
    "Bookshelves with positions": "to-read (#50)",
    "Exclusive Shelf": "to-read",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 0,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
  {
    "Book Id": 55230079,
    Title: "Dear Martin",
    Author: "Nic Stone",
    "Author l-f": "Stone, Nic",
    "Additional Authors": "",
    ISBN: "",
    ISBN13: null,
    "My Rating": 4,
    "Average Rating": 4.37,
    Publisher: "Ember",
    Binding: "Kindle Edition",
    "Number of Pages": 219,
    "Year Published": 2017,
    "Original Publication Year": 2017,
    "Date Read": "2020/12/14",
    "Date Added": "2020/12/13",
    Bookshelves: "",
    "Bookshelves with positions": "",
    "Exclusive Shelf": "read",
    "My Review": "",
    Spoiler: "",
    "Private Notes": "",
    "Read Count": 1,
    "Recommended For": "",
    "Recommended By": "",
    "Owned Copies": 0,
    "Original Purchase Date": "",
    "Original Purchase Location": "",
    Condition: "",
    "Condition Description": "",
    BCID: "",
  },
];
export { bookMockDataA, bookMockDataB };
